---
- hosts: frontend
  become: yes
  tasks:
    - name: Set up permissions for magento folders
      file:
        path: "{{ nginx_magento_server_doc_root }}/{{ item }}"
        mode: 0777
        state: directory
        recurse: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      with_items:
        - "var"
        - "media"
        - "app/etc"
    - name: Generate local.xml
      template:
        src: templates/local.j2
        dest: "/tmp/local.xml"
        mode: 0775
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Move local.xml from /tmp into "{{ nginx_magento_server_doc_root }}/app/etc/"
      command: mv /tmp/local.xml {{ nginx_magento_server_doc_root }}/app/etc/local.xml
    - name: Enable Magento cron
      cron: name="magento cron" minute="*/1" job="{{ nginx_magento_server_doc_root }}/cron.sh" user="{{ ansible_user }}"
      when: magento_enable_cron == true
    - name: Clean helpfull /tmp folder :-)
      file: path="/tmp/{{ item }}" state=absent
      with_items:
        - "*.sql"
        - "*.tar.gz"
        - "composer-installer.php"
        - "xdebug-2.3.3/"
        - "xdebug-2.3.3.tgz"
